## Numpy

In [1]:
import numpy as np

### Zadanie 1.

Stwórz losową tablicę 10,000 liczb, następnie do każdego elementu dodaj 1. Następnie napisz dokładnie tę samą funkcję używając `numpy` i jego tablic. Porównaj czas działania swoich rozwiązań.

In [2]:
import random
import time

def arr_python():
    normal_arr = [random.random() for _ in range(10000)]
    return [x + 1 for x in normal_arr]

def arr_numpy():
    numpy_arr = np.random.rand(10000)
    return np.add(numpy_arr, 1)

start_time_python = time.time()
result_python = arr_python()
end_time_python = time.time()
time_python = end_time_python - start_time_python


start_time_python = time.time()
result_python = arr_numpy()
end_time_python = time.time()
time_numpy = end_time_python - start_time_python

if time_python > time_numpy:
    print("Python jest wolniejszy!")
else:
    print("Numpy jest wolniejsze!")

Python jest wolniejszy!


### Zadanie 2.

Napisz funkcje obliczajaca $\sin(x) + \cos(x)$ dla kazdego elementu tablicy 10,000 losowych liczb używając pętli oraz używając numpy, porownaj ich szybkość podobnie jak w poprzednim zadaniu.

In [3]:
from math import sin, cos


def calc_loop(array):
    result = []
    for x in array:
        result.append(sin(x) + cos(x))
    return result

def calc_numpy(array):
    return np.sin(array) + np.cos(array)

random_array = np.random.rand(10000)

start_time = time.time()
result_with_loop = calc_loop(random_array)
end_time = time.time()
loop_time = end_time - start_time


start_time = time.time()
result_with_numpy = calc_numpy(random_array)
end_time = time.time()
numpy_time = end_time - start_time

if loop_time > numpy_time:
    print("Python jest wolniejszy!")
else:
    print("Numpy jest wolniejsze!")


Python jest wolniejszy!


### Zadanie 3.

Napisz wydajniejszą forme następujących funkcji. Dopisz do każdej test potwierdzający szybkość zaproponowanego rozwiązania.

In [4]:
def cube_sum(x):
    """Zwraca sume szescianow elementow"""
    result = 0
    for i in range(len(x)):
        result += x[i] ** 3
    return result

def almost_variance(x):
    """Oblicza 1/n * SUM (x_i - mean(x))^4"""
    m = sum(x) / len(x)
    result = 0
    for i in range(len(x)):
        result += (x[i] - m) ** 4
    result /= len(x)
    return result

def numpy_cube_sum(x):
    """Zwraca sume szescianow elementow"""
    return np.sum(x ** 3)


def numpy_almost_variance(x):
    """Oblicza 1/n * SUM (x_i - mean(x))^4"""
    n = x.mean()
    return np.mean((x - n) ** 4)

array = np.random.randint(250, size=250)

start = time.time()
cube_sum(array)
period = time.time() - start
print("1, python: ", period)

start = time.time()
numpy_cube_sum(array)
period = time.time() - start
print("1, numpy: ", period)

start = time.time()
almost_variance(array)
period = time.time() - start
print("2, python: ", period)

start = time.time()
numpy_almost_variance(array)
period = time.time() - start
print("2, numpy: ", period)

1, python:  9.703636169433594e-05
1, numpy:  5.7220458984375e-05
2, python:  7.700920104980469e-05
2, numpy:  7.796287536621094e-05


### Zadanie 4.

Wykorzystujac `broadcasting` (patrz na rysunek poniżej) stwórz tabliczkę mnożenia tzn. tablice $A$ taka, ze $$A_{ij} = i \cdot j\;\;\;\;\; \forall i,j \in \{1,\dots,10\}$$

Czy potrafisz wykonać to jednym poleceniem, nie używajac przy tym petli/comprehensions?

<img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">

In [5]:
A = np.arange(1, 11).reshape((10, 1)) * np.arange(1,11)
print(A)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Zad 5.

Wygeneruj losową tablice `10 x 5`, która będzie reprezentować `10` punktów w `5` wymiarowej przestrzeni. Napisz funkcje, która policzy odleglość euklidesową pomiędzy każdą parą punktów, czy potrafisz zrobić to **bez użycia żadnych pętli/comprehensions**? 

Przypomnienie, dla dwóch wektorów: $x$ i $y$ $$d_{e}(x,y) = \| x - y \|^2_2 = \sum_{i=1}^d (x_i - y_i)^2 $$

In [6]:
def calc_euclidean_distance(arr):
    n = arr.shape[0]
    res = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1, n):
            res[i, j] = np.linalg.norm(arr[i, :] - arr[j, :])**2
            res[j, i] = res[i, j]
    return res

tab = np.random.randn(10,5)
print (tab)

print(np.round(calc_euclidean_distance(tab), decimals=3))

[[-0.24117308  0.83275576 -0.63334494 -1.57945746 -0.52652454]
 [-0.42613902  1.33888347  0.03434141  0.20736965 -1.19380724]
 [-0.44960317 -0.39786497  0.80079625 -0.31092307 -0.24208957]
 [-1.54031093  1.50054677 -0.10097716  1.10895664 -1.88810577]
 [ 0.61678728 -0.16784979  0.90805708 -0.38216357  0.16651971]
 [ 0.88245554 -0.96744781 -1.44132464  0.63638007  0.45947134]
 [ 1.1140604  -0.96371812 -1.33000357  0.51999605 -0.05337622]
 [ 0.59577021 -0.55054595  0.18455947  1.05166494  0.06874398]
 [ 0.74180555  1.69421879 -0.62203093  0.70047246 -1.46245697]
 [-1.67825067 -0.39306876 -1.7693012   0.9843741   0.54982004]]
[[ 0.     4.374  5.305 11.499  6.027 11.038 10.181 10.56   7.783 12.59 ]
 [ 4.374  0.     4.779  2.581  6.319 12.127 10.934  6.944  2.237 11.465]
 [ 5.305  4.779  0.    10.332  1.374  8.515  8.032  3.449 10.333 10.42 ]
 [11.499  2.581 10.332  0.    14.9   19.492 18.342 12.684  5.865 12.347]
 [ 6.027  6.319  1.374 14.9    0.     7.353  6.752  2.736  9.65  14.501]
 [11

### Zad 6.

Napisz funkcje do "wybielania" zbioru punktow, tj. aplikowania następującej transformacji (ponownie, zrób to bez użycia pętli etc.)
$$
\mathrm{white}(X)_{ij} = \frac{X_{ij} - \mu_j}{\sigma_j}
$$
gdzie $\mu_j$ to srednia po $j$ej kolumnie, a $\sigma_j$ to odchylenie standardowe po tej kolumnie, np.

$$
\mathrm{white}\left ( \left [ \begin{matrix} 
0& 1\\
2& 3\\
4& 5\\
6& 7\\
8& 9
\end{matrix} \right ] \right ) = 
\left [ \begin{matrix} 
-1.41421356& -1.41421356\\
-0.70710678& -0.70710678\\
0.        &  0.        \\
0.70710678&  0.70710678\\
1.41421356&  1.41421356
\end{matrix} \right ]
$$

W szczególności średnia po poszczególnych kolumnach nowej macierzy powinna wynosić `0` a odchylenie standardowe `1`.

### Zad 7.

Majac dana tablice dowolnie wymiarowa (dla uproszczenia mozesz przyjac ze jedno lub dwu) oraz liczbe `x` znajdz najblizsza wartosc `x` w `A`, tzn. 

$$
\mathrm{closest}(x, A) = \arg\min_{a\in A}| x - a| 
$$

np. 

$$
\mathrm{closest}(1.5, [1, -4, 3]) = 1
$$

Ponownie, czy potrafisz zrobic to bez petli, etc.?


### Zad 8.

Zaimplementuj proste liczenie wartosci wielomianu o zadanych wspolczynnikach (analogie `np.poly1d`), czyli funkcje

$$
\mathrm{poly}(x, a) = a_0 + a_1 x + a_2 x^2 + \dots + a_k x^k = \sum_{i=1}^k a_i x^i
$$

Czy potrafisz zrobic to jednolinijkowo bez uzycia petli, etc. (oraz oczywiście `np.poly1d`). 
Może Ci się przydać metoda `cumprod`.

## Obrazki

Do wyświetlania obrazków w notebooku potrzebny będzie `matplotlib`. W PyCharmie można użyć `imshow` z biblioteki `scipy`.

In [7]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [8]:
img = mpimg.imread('images/doggo.png')
plt.imshow(img);

FileNotFoundError: [Errno 2] No such file or directory: 'images/doggo.png'

### Zad 9.

Napisz funckje do przetwarzania obrazu do skali szarości wg wzoru:

$$ 0.2126 \times R + 0.7152 \times  G + 0.0722 \times B $$

### Zadanie 10.

Wyłącznie za pomocą metod numpy napisz kod do interpolacji liniowej pomiędzy parą punktów (dowolnej wymiarowości) wg wzoru:

$$ x_i = \lambda x_1 + (1 - \lambda) x_2$$

Kod powinien od razu generować interpolacje dla wielu wartości $\lambda$, np dla 10 różnych $\lambda \in \{0, 0.1, 0.2, \dots, 1\}$