## Numpy

In [1]:
import numpy as np

### Zadanie 1.

Stwórz losową tablicę 10,000 liczb, następnie do każdego elementu dodaj 1. Następnie napisz dokładnie tę samą funkcję używając `numpy` i jego tablic. Porównaj czas działania swoich rozwiązań.

In [2]:
import random
import time

def arr_python():
    normal_arr = [random.random() for _ in range(10000)]
    return [x + 1 for x in normal_arr]

def arr_numpy():
    numpy_arr = np.random.rand(10000)
    return np.add(numpy_arr, 1)

start_time_python = time.time()
result_python = arr_python()
end_time_python = time.time()
time_python = end_time_python - start_time_python


start_time_python = time.time()
result_python = arr_numpy()
end_time_python = time.time()
time_numpy = end_time_python - start_time_python

if time_python > time_numpy:
    print("Python jest wolniejszy!")
else:
    print("Numpy jest wolniejsze!")

Python jest wolniejszy!


### Zadanie 2.

Napisz funkcje obliczajaca $\sin(x) + \cos(x)$ dla kazdego elementu tablicy 10,000 losowych liczb używając pętli oraz używając numpy, porownaj ich szybkość podobnie jak w poprzednim zadaniu.

In [3]:
from math import sin, cos


def calc_loop(array):
    result = []
    for x in array:
        result.append(sin(x) + cos(x))
    return result

def calc_numpy(array):
    return np.sin(array) + np.cos(array)

random_array = np.random.rand(10000)

start_time = time.time()
result_with_loop = calc_loop(random_array)
end_time = time.time()
loop_time = end_time - start_time


start_time = time.time()
result_with_numpy = calc_numpy(random_array)
end_time = time.time()
numpy_time = end_time - start_time

if loop_time > numpy_time:
    print("Python jest wolniejszy!")
else:
    print("Numpy jest wolniejsze!")


Python jest wolniejszy!


### Zadanie 3.

Napisz wydajniejszą forme następujących funkcji. Dopisz do każdej test potwierdzający szybkość zaproponowanego rozwiązania.

In [5]:
def cube_sum(x):
    """Zwraca sume szescianow elementow"""
    result = 0
    for i in range(len(x)):
        result += x[i] ** 3
    return result

def almost_variance(x):
    """Oblicza 1/n * SUM (x_i - mean(x))^4"""
    m = sum(x) / len(x)
    result = 0
    for i in range(len(x)):
        result += (x[i] - m) ** 4
    result /= len(x)
    return result

def numpy_cube_sum(x):
    """Zwraca sume szescianow elementow"""
    return np.sum(x ** 3)


def numpy_almost_variance(x):
    """Oblicza 1/n * SUM (x_i - mean(x))^4"""
    n = x.mean()
    return np.mean((x - n) ** 4)

array = np.random.randint(250, size=250)

start = time.time()
cube_sum(array)
period = time.time() - start
print("1, python: ", period)

start = time.time()
numpy_cube_sum(array)
period = time.time() - start
print("1, numpy: ", period)

start = time.time()
almost_variance(array)
period = time.time() - start
print("2, python: ", period)

start = time.time()
numpy_almost_variance(array)
period = time.time() - start
print("2, numpy: ", period)

1, python:  7.390975952148438e-05
1, numpy:  0.0001010894775390625
2, python:  0.0001418590545654297
2, numpy:  0.00010991096496582031


### Zadanie 4.

Wykorzystujac `broadcasting` (patrz na rysunek poniżej) stwórz tabliczkę mnożenia tzn. tablice $A$ taka, ze $$A_{ij} = i \cdot j\;\;\;\;\; \forall i,j \in \{1,\dots,10\}$$

Czy potrafisz wykonać to jednym poleceniem, nie używajac przy tym petli/comprehensions?

<img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">

In [6]:
A = np.arange(1, 11).reshape((10, 1)) * np.arange(1,11)
print(A)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Zad 5.

Wygeneruj losową tablice `10 x 5`, która będzie reprezentować `10` punktów w `5` wymiarowej przestrzeni. Napisz funkcje, która policzy odleglość euklidesową pomiędzy każdą parą punktów, czy potrafisz zrobić to **bez użycia żadnych pętli/comprehensions**? 

Przypomnienie, dla dwóch wektorów: $x$ i $y$ $$d_{e}(x,y) = \| x - y \|^2_2 = \sum_{i=1}^d (x_i - y_i)^2 $$

In [11]:
def calc_euclidean_distance(arr):
    n = arr.shape[0]
    res = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1, n):
            res[i, j] = np.linalg.norm(arr[i, :] - arr[j, :])**2
            res[j, i] = res[i, j]
    return res

tab = np.random.randn(10,5)
print (tab)

print(np.round(calc_euclidean_distance(tab), decimals=3))

[[ 4.07783893e-01  1.83904001e+00  1.42540825e+00  1.16985264e+00
  -5.18134488e-01]
 [ 5.27932730e-02 -8.26571405e-01 -1.13626443e-01 -2.00687533e-01
   3.85121892e-01]
 [ 5.24069825e-01 -1.23570584e+00  3.64711586e-01  2.34750640e-01
  -2.17840515e-02]
 [ 1.13336696e+00 -1.09770210e+00 -5.96869816e-01 -8.40929737e-01
   1.78668887e+00]
 [-1.54648925e+00  9.53787938e-05 -1.79618649e+00 -2.15565107e+00
  -4.14731712e-01]
 [-4.97940651e-01 -2.15071560e+00  1.55688476e-02 -2.66118008e+00
  -5.78687063e-01]
 [ 6.44707816e-01 -3.37162029e-01 -2.79879465e-03 -3.50957360e-01
   6.40389681e-01]
 [-1.05934180e+00  1.48514737e-01 -2.36584753e-01  3.01821160e-01
   2.51758257e+00]
 [-1.73447842e-01 -9.44539164e-01  6.83939060e-01  4.11245530e-01
   1.78886369e-01]
 [-4.49479762e-01 -1.06209454e+00 -8.59099634e-01  7.13655968e-01
  -1.05670166e+00]]
[[ 0.    12.294 11.713 22.596 28.649 33.407 10.487 17.742  9.697 14.869]
 [12.294  0.     0.973  3.849 10.534  9.056  0.69   7.003  1.118  3.778]
 [1

### Zad 6.

Napisz funkcje do "wybielania" zbioru punktow, tj. aplikowania następującej transformacji (ponownie, zrób to bez użycia pętli etc.)
$$
\mathrm{white}(X)_{ij} = \frac{X_{ij} - \mu_j}{\sigma_j}
$$
gdzie $\mu_j$ to srednia po $j$ej kolumnie, a $\sigma_j$ to odchylenie standardowe po tej kolumnie, np.

$$
\mathrm{white}\left ( \left [ \begin{matrix} 
0& 1\\
2& 3\\
4& 5\\
6& 7\\
8& 9
\end{matrix} \right ] \right ) = 
\left [ \begin{matrix} 
-1.41421356& -1.41421356\\
-0.70710678& -0.70710678\\
0.        &  0.        \\
0.70710678&  0.70710678\\
1.41421356&  1.41421356
\end{matrix} \right ]
$$

W szczególności średnia po poszczególnych kolumnach nowej macierzy powinna wynosić `0` a odchylenie standardowe `1`.

### Zad 7.

Majac dana tablice dowolnie wymiarowa (dla uproszczenia mozesz przyjac ze jedno lub dwu) oraz liczbe `x` znajdz najblizsza wartosc `x` w `A`, tzn. 

$$
\mathrm{closest}(x, A) = \arg\min_{a\in A}| x - a| 
$$

np. 

$$
\mathrm{closest}(1.5, [1, -4, 3]) = 1
$$

Ponownie, czy potrafisz zrobic to bez petli, etc.?


### Zad 8.

Zaimplementuj proste liczenie wartosci wielomianu o zadanych wspolczynnikach (analogie `np.poly1d`), czyli funkcje

$$
\mathrm{poly}(x, a) = a_0 + a_1 x + a_2 x^2 + \dots + a_k x^k = \sum_{i=1}^k a_i x^i
$$

Czy potrafisz zrobic to jednolinijkowo bez uzycia petli, etc. (oraz oczywiście `np.poly1d`). 
Może Ci się przydać metoda `cumprod`.

## Obrazki

Do wyświetlania obrazków w notebooku potrzebny będzie `matplotlib`. W PyCharmie można użyć `imshow` z biblioteki `scipy`.

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [ ]:
img = mpimg.imread('images/doggo.png')
plt.imshow(img);

### Zad 9.

Napisz funckje do przetwarzania obrazu do skali szarości wg wzoru:

$$ 0.2126 \times R + 0.7152 \times  G + 0.0722 \times B $$

### Zadanie 10.

Wyłącznie za pomocą metod numpy napisz kod do interpolacji liniowej pomiędzy parą punktów (dowolnej wymiarowości) wg wzoru:

$$ x_i = \lambda x_1 + (1 - \lambda) x_2$$

Kod powinien od razu generować interpolacje dla wielu wartości $\lambda$, np dla 10 różnych $\lambda \in \{0, 0.1, 0.2, \dots, 1\}$