## Zadanie 21 (hard)

Wykonaj wykres 3D funkcji
$$
z = x^2-y^2
$$

oraz rysunek poziomic tej funkcji. Tak jak poniżej

![alt text](kol02_pytania/images/image04.png "obrazek")

![alt text](kol02_pytania/images/image05.png "obrazek")

Rozwiązania studentów

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

%matplotlib inline
x = np.arange(-3.0, 3.0, 0.01)
y = np.arange(-3.0, 3.0, 0.01)

X, Y = np.meshgrid(x, y)
zs = np.array([x * x - y * y for x, y in zip(np.ravel(X), np.ravel(Y))])
Z = zs.reshape(X.shape)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(X, Y, Z, cmap=cm.viridis)



In [ ]:
plt.contourf(X, Y, Z, cmap=cm.viridis)

## Zadanie 9 (hard)
We wczytanym poniżej zbiorze danych imion wypisz wszystkie imiona, których pod względem częstości występowania jest najwięcej, najmniej i te których jest dokładnie tyle ile wynosi mediana wystąpień. W rozwiązaniu użyj pakietu `pandas`

Dane możesz wczytać wykorzystując poniższy kod

```python
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/\
US_Baby_Names/US_Baby_Names_right.csv')
```

In [6]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/\
US_Baby_Names/US_Baby_Names_right.csv')

df = df.drop('Year', axis=1).drop('Unnamed: 0', axis=1).drop('Id', axis=1)
names = df.groupby('Name').sum()

# min
print(names[names.Count == names.Count.min()].index.values)

# max
print(names[names.Count == names.Count.max()].index.values)

# median
print(names[names.Count == names.Count.median()])

['Aadarsh' 'Aadin' 'Aaima' ... 'Zykeriah' 'Zykierra' 'Zymari']
['Jacob']
         Count
Name          
Aishani     49
Alara       49
Alysse      49
Ameir       49
Anely       49
...        ...
Sriram      49
Trinton     49
Vita        49
Yoni        49
Zuleima     49

[66 rows x 1 columns]


/var/folders/xh/7q_pyjm16ks_m5x6b_59zgk40000gn/T/ipykernel_95714/2758385152.py:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  names = df.groupby('Name').sum()


In [5]:
import pandas as pd

# Wczytanie danych

# Najczęściej występujące imię
most_common_name = df['Name'].value_counts().idxmax()

# Najrzadziej występujące imię
least_common_name = df['Name'].value_counts().idxmin()

# Imiona występujące dokładnie tyle razy, ile wynosi mediana
median_frequency_names = df['Name'].value_counts()[df['Name'].value_counts() == df['Name'].value_counts().median()].index.tolist()

# Wyświetlenie wyników
print("Najczęściej występujące imię:", most_common_name)
print("Najrzadziej występujące imię:", least_common_name)
print("Imiona występujące dokładnie tyle razy, ile wynosi mediana wystąpień:", median_frequency_names)


Najczęściej występujące imię: Riley
Najrzadziej występujące imię: Grettell
Imiona występujące dokładnie tyle razy, ile wynosi mediana wystąpień: ['Oluwatobi', 'Evanna', 'Rasheen', 'Amer', 'Lukasz', 'Clarity', 'Han', 'Jelissa', 'Eliya', 'Emmaly', 'Tovia', 'Emelly', 'Keigan', 'Elizaveta', 'Mattox', 'Janeli', 'Esli', 'Izek', 'Jazmynn', 'Irena', 'Eliora', 'Jennalyn', 'Leni', 'Cypress', 'Andriana', 'Ezekial', 'Lucila', 'Darling', 'Nicodemus', 'Saketh', 'Kaiyah', 'Jacquelyne', 'Mechel', 'Johnatan', 'Monty', 'Riot', 'Otoniel', 'Aran', 'Augusto', 'Adylene', 'Triana', 'Candelario', 'Shelsy', 'Rebecka', 'Dalyn', 'Codey', 'Naraly', 'Elliotte', 'Mariann', 'Yaira', 'Skylie', 'Ayannah', 'Kunal', 'Eliab', 'Dillinger', 'Nyree', 'Issaiah', 'Maika', 'Jalani', 'Leighann', 'Jonnathan', 'Alara', 'Azlyn', 'Jakhari', 'Tuff', 'Aristeo', 'Fishel', 'Texas', 'Elizah', 'Adelie', 'Judas', 'Edgard', 'Eladio', 'Daphnie', 'Azure', 'Yoni', 'Lamiya', 'Irais', 'Milca', 'Lucus', 'Tal', 'Nakai', 'Nishant', 'Katelynne', 'R

## Zadanie 8 (hard)
Zwizualizuj poniższą próbkę danych na 3 wykresach na jedne figurze (plt.figure), na pierwszym ma się znaleźć histogram wartości pierwszego wymiaru z próbki, na drugim wylosowane punkty na płaszczyźnie, na trzecim histogram wartości drugiego wymiaru.

```python
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

X = np.random.multivariate_normal(mean=[0, 0], cov=[[1, 0.5], [0.5, 1]], size=1000)
```

Postaraj się osiągnąć efekt zbliżony do:

![alt text](kol02_pytania/images/image02.png "obrazek")

Rozwiązania studentów

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

X = np.random.multivariate_normal(mean=[0, 0], cov=[[1, 0.5], [0.5, 1]], size=1000)

In [ ]:
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np


X = np.random.multivariate_normal(mean=[0, 0], cov=[[1, 0.5], [0.5, 1]], size=1000)

plt.subplot(331)
plt.hist(X[:, 0])

plt.subplot(332)
plt.scatter(X[:, 0], X[:, 1])

plt.subplot(333)
plt.hist(X[:, 1])

plt.show()


## Zadanie 17 (medium)
Przepisz poniższą funkcję aby działała około 100 razy szybciej dla zadanego wektora `x`

```python
import numpy as np

def m_sin(x):
    r = np.zeros_like(x) 
    for i in range(len(x)):
        r[i] = np.sin(x[i])
    return r

x = np.linspace(0, 1, 1000000)

```

In [ ]:
import numpy as np
def m_sin(x):
    r = np.zeros_like(x) 
    for i in range(len(x)):
        r[i] = np.sin(x[i])
    return r

x = np.linspace(0, 1, 1000000)

In [ ]:
%timeit m_sin(x)

Rozwiązania studentów

In [ ]:
import numpy as np

def m_sin(x):
    return np.sin(x)

In [ ]:
%timeit m_sin(x)

Rozwiązania studentów

## Zadanie 22 (easy)
Jak zoptymalizować działanie poniższej pętli, tak aby czas jej działania skrócił się znacząco

```python
from math import sin

def loop(num):
    result = 0
    for i in range(num):
        result += i * sin(num)
    return result
```

W testach czas dla `num = 100000` skrócił się z 20.6 ms do  5.56 ms.

Rozwiązania studentów

In [ ]:
def loop(num):
    sinus = sin(num)
    return (sum(x* sinus) for x in range(0, num))

In [ ]:
%timeit loop(100000)

## Zadanie 18 (medium)
Przygotuj wykres będący zwieńczeniem poniższego kodu

```python
import numpy as np
import matplotlib.pyplot as plt
from numpy import exp, sin, cos

def g(y):
    return exp(-y)*cos(5*y)

def h(y):
    return exp(-(3./4)*y)*cos(2*y)

y = np.linspace(0, 10, 1001)
```

w Twoim rozwiązaniu postaraj się zbliżyć do

![alt text](kol02_pytania/images/image03.png "obrazek")

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import exp, sin, cos

def g(y):
    return exp(-y)*cos(5*y)

def h(y):
    return exp(-(3./4)*y)*cos(2*y)

y = np.linspace(0, 10, 1001)

# Zakres wartości y
y = np.linspace(0, 10, 1001)

# Wygeneruj wykres dla funkcji g(y)
plt.figure()
# plt.subplot(1, 2, 1)
plt.plot(y, g(y), label='g(y)')
plt.title('Wykres funkcji g(y)')
plt.xlabel('y')
plt.ylabel('g(y)')
plt.legend()

# Wygeneruj wykres dla funkcji h(y)
# plt.subplot(1, 2, 2)
plt.plot(y, h(y), label='h(y)', color='orange')
plt.title('Wykres funkcji h(y)')
plt.xlabel('y')
plt.ylabel('h(y)')
plt.legend()

# Wyświetl wykresy
plt.show()
## Rozwiązania studentów

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import exp, sin, cos

def g(y):
    return exp(-y)*cos(5*y)

def h(y):
    return exp(-(3./4)*y)*cos(2*y)

y = np.linspace(0, 10, 1001)

In [ ]:
plt.figure()
plt.title('Wykres funkcji g i h')
plt.xlabel('$y$')
plt.ylabel('$g(y), h(y)$')
# dodanie legendy
plt.plot(y,g(y), 'r', label=r'g')
plt.plot(y,h(y), '--k', label='h')
plt.legend(loc='upper right') # pozycja legendy
plt.show()


## Zadanie 15 (medium)
Napisz program, który dla zadanej liczby naturalnej `n` wygeneruje macierze zwierającą wszystkie liczby od `0` do `n-1`, np. dla `n=100` mamy
```python
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
```
Macierz zostanie wygenerowana tylko, gdy `n` jest kwadratem jakiejś liczby w przeciwnym przypadku zostanie rzucony wyjątek `ValueError`.
```python
def matrix(n):
    pass
```

In [ ]:
import numpy as np
import math 
def matrix(n):
    sqr_n = math.sqrt(n)
    if sqr_n.is_integer:
        sqr_n = int(sqr_n)
        return np.arange(n).reshape(sqr_n, sqr_n)
    else:
        raise ValueError
print(np.array_equal(matrix(4),np.array([[0, 1],[2, 3]])))
# matrix(5) # rzuci wyjątek ValueError
print(np.array_equal(matrix(16), np.array([[ 0,  1,  2,  3], [ 4,  5,  6,  7], [ 8,  9, 10, 11],[12, 13, 14, 15]])))

Rozwiązania studentów

In [ ]:
import numpy as np
def matrix(n):
    w = np.sqrt(n)
    if int(w) != w:
        raise ValueError()
    w = int(w)
    return np.arange(0, n).reshape(w, w)
print(np.array_equal(matrix(4),np.array([[0, 1],[2, 3]])))
try:
    matrix(5) # rzuci wyjątek ValueError
except:
    print('ok')
print(np.array_equal(matrix(16), np.array([[ 0,  1,  2,  3], [ 4,  5,  6,  7], [ 8,  9, 10, 11],[12, 13, 14, 15]])))

## Zadanie 2 (easy)
Napisz funkcję która będzie rozwiązywać problem najmnijszych kwadratów. Matematycznie rozwiązanie tego problemu to:
$$ (X^TX)^{-1}X^Tb $$

Nie wolno korzystać z funkcji `pinv` ani funkcji bezpośrednio rozwiązujących ten problem.

```python
import numpy as np

def lsq(X, b):
    pass
```

In [ ]:
import numpy as np
from numpy.linalg import inv
def lsq(X, b):
    X = np.matrix(X)
    b = np.matrix(b).T
    return np.ravel((X.T*X)**-1 * (X.T*b))

X = np.array([[1, 2], [2, 3], [4, 4]])
b = [1, 2, 3]
print(np.isclose(lsq(X, b), [0.39393939,0.36363636]))

X = np.array([[1, -1], [0, 3], [4, 4]])
b = [1, 2, 2]
print(np.isclose(lsq(X, b), [ 0.1797235,0.39631336]))

Rozwiązania studentów

In [ ]:
def lsq(X, b):
    X = np.matrix(X)
    b = np.matrix(b).T
    return np.ravel(((X.T * X) ** -1) * (X.T * b))
X = np.array([[1, 2], [2, 3], [4, 4]])
b = [1, 2, 3]
print(np.isclose(lsq(X, b), [0.39393939,0.36363636]))

X = np.array([[1, -1], [0, 3], [4, 4]])
b = [1, 2, 2]
print(np.isclose(lsq(X, b), [ 0.1797235,0.39631336]))

## Zadanie 7 (medium)
Wylosuj z dwóch różnych rozkładów normlanych o odchyleniu standardowym 1 i średnich odpowiednio -1 i 1 po 1000 liczb, następnie zwizaulizuj te dwie próbki na jednym wykresie za pomocą histogramów, różnymi kolorami, tak aby była wyraźnie widoczna część wspólna dwóch histogramów.

Osiągnij wynik zbliżony do następujacego
![alt text](kol02_pytania/images/image01.png "obrazek")

W rozwiązaniu podaj procedurę generującą wykres. Możesz wykorzystać:

```python
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
```

In [ ]:
import matplotlib.pyplot as plt

sample1 = np.random.randn(1000) - 1
sample2 = np.random.randn(1000) + 1

a = np.random.normal(loc=-1, scale=1, size=1000)
b = np.random.normal(loc=1, scale=1, size=1000)

plt.hist(a)
plt.hist(b, alpha = 0.6)
plt.show()


## Zadanie 6 (easy)
Używając biblioteki **numpy** zaimplementuj funckje `normalize_rows`, która normalizuje wiersze macierzy tak by każdy z nich miał normę euklidesową 1. Możesz użyć funckji `numpy.linalg.norm`. Następnie wylosuj macierz z wartościami z przedziału `[0,1]` o 20 wierszach i 5 kolumnach i znormalizuj ją swoją funkcją.

```python
import numpy as np

def normalize_rows(X):
    pass
```

In [ ]:
def normalize_rows(X):
   return X/np.linalg.norm(X, keepdims = True)

X = np.random.rand(20,5) # uzupełnij zgodnie z treścią zadania
X_norm = normalize_rows(X)

print(all((np.linalg.norm(X_norm, axis=1) - np.ones(20)) < 1e-8))

Rozwiązania studentów

In [ ]:
def normalize_rows(X):
    row_sums = X.sum(axis=1)
    return X / row_sums[:, np.newaxis]

X = np.random.rand(20, 5)
X_norm = normalize_rows(X)

print(all((np.linalg.norm(X_norm, axis=1) - np.ones(20)) < 1e-8))

In [ ]:
import numpy as np

# zwraca ślad macierzy 2D
def get_trace(array):
  return np.trace(array)


import numpy as np

def outer_product(vec1, vec2):
    return np.outer(vec1, vec2)

  # fcja zwraca produkt zewnętrzny dwóch wektorów

def get_common(arr1, arr2):
  # funcja zwraca unikalne wspólne elementy dwóch wektorów (te same elementy na tych samych pozycjach)
  return np.unique(arr1[arr1 == arr2])

  import pandas as pd

def series_uppercase(series):
    return series.str.capitalize()
  # zwraca Series, w którym każdy element zaczyna się wielką literą


class FunCount(object):
    # uzupełnij kod klasy tak, żeby obiekt "dekorował" funkcje i liczył jej wywołania
    cnt = 0
    def __init__(self, f):
        self.cnt = 0
        self.f = f
    def __call__(self, *args):
        self.cnt = self.cnt + 1
        return sum([arg for arg in args])
    def __str__(self):
        return '"fun" was called {} times.'.format(self.cnt)

def add_min_max(df):
   df['max'] = df[[0, 1, 2, 3]].max(axis=1)
   df['min'] = df[[0, 1, 2, 3]].min(axis=1)
  # fcja dodaje kolumny 'min' oraz 'max' zawierające minumum i maksimum każdego wiersza
ZAPIERDALA


# zwraca elementy serii na pozycjach pos

def get_series_at_positions(series, pos):
  return series.loc[pos]

  class A(object):
    # uzupełnij kod klasy tak, aby w polu cnt była liczba utworzonych obiektów tej klasy
    cnt = 0
    def __init__(self):
        A.cnt += 1
        self.id = A.cnt



# narysuj wykres oraz zaznacz minima i maksima lokalne tak jak na rysunku
from scipy.signal import argrelextrema
def plot_points(X):
  df = pd.DataFrame(X, columns=['data'])
  n = 2
  df['min'] = df.iloc[argrelextrema(df.data.values, np.less_equal,
                    order=n)[0]]['data']
  df['max'] = df.iloc[argrelextrema(df.data.values, np.greater_equal,
                    order=n)[0]]['data']

  # Plot results

  plt.scatter(df.index, df['min'], c='r')
  plt.scatter(df.index, df['max'], c='g')
  plt.plot(df.index, df['data'])
  plt.show()

steps = [-1,+1]
walk = np.random.choice(steps, 200).cumsum()

plot_points(walk)

# niby lepsze od tego wyzej
def rescale(X):
    return X / X.sum(axis=1)[:, np.newaxis]



# def plot_log(x, y):

#     plt.plot(x,y)
#     plt.yscale('log')
#     plt.show()

def plot_log(x, y):
  plt.plot(x,y)
  plt.xlabel('x')
  plt.ylabel('$e^x$')
  plt.yscale('log')
  plt.show()



def get_union(arr1, arr2):
  # fcja zwraca iloczyn mnogościowy dwóch wektorów
  return list(set(arr1).intersection(arr2))


def mirror(arr):
    return np.flip(arr, axis=None)
  # fcja odbija elementy macierzy wzgl. "drugiej" przekątnej.


import pandas as pd

def series_difference(series1, series2):
  # zwraca różnicę mnogościową dwóch serii
  result = []
  for i in series1.values:
    if i not in series2.values:
      result.append(i)
      
  return result


def mirror(arr):
  # fcja odbija elementy macierzy wzgl. "drugiej" przekątnej.
  return np.rot90(np.rot90(np.rot90(np.fliplr(arr))))
